package br.com.feob.Enum;

public enum GrupoConta {

    ATIVO, ATIVO_CIRCULANTE, ATIVO_NAO_CIRCULANTE, PASSIVO, FORNECEDOR, PASSIVO_CIRCULANTE, PASSIVO_NAO_CIRCULANTE, PL, DRE, DISPONIVEL, ESTOQUE, CONTAS_RECEBER,
    RECEITA_VENDAS, CUSTO_MERCADORIA
    
}
